package com.jinxin.manager.dao.base;

import com.jinxin.manager.po.BbsMsg;
import com.jinxin.manager.po.BbsMsgExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface BbsMsgMapper {
	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table t_board_msg
	 *
	 * @mbg.generated
	 */
	long countByExample(BbsMsgExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table t_board_msg
	 *
	 * @mbg.generated
	 */
	int deleteByExample(BbsMsgExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table t_board_msg
	 *
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table t_board_msg
	 *
	 * @mbg.generated
	 */
	int insert(BbsMsg record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table t_board_msg
	 *
	 * @mbg.generated
	 */
	int insertSelective(BbsMsg record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table t_board_msg
	 *
	 * @mbg.generated
	 */
	List<BbsMsg> selectByExample(BbsMsgExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table t_board_msg
	 *
	 * @mbg.generated
	 */
	BbsMsg selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table t_board_msg
	 *
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") BbsMsg record, @Param("example") BbsMsgExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table t_board_msg
	 *
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") BbsMsg record, @Param("example") BbsMsgExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table t_board_msg
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(BbsMsg record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table t_board_msg
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKey(BbsMsg record);
}