package com.jinxin.manager.dao.base;

import com.jinxin.manager.po.ImgInfo;
import com.jinxin.manager.po.ImgInfoExample;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface ImgInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_info
     *
     * @mbg.generated
     */
    long countByExample(ImgInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_info
     *
     * @mbg.generated
     */
    int deleteByExample(ImgInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_info
     *
     * @mbg.generated
     */
    int insert(ImgInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_info
     *
     * @mbg.generated
     */
    int insertSelective(ImgInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_info
     *
     * @mbg.generated
     */
    List<ImgInfo> selectByExample(ImgInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_info
     *
     * @mbg.generated
     */
    ImgInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ImgInfo record, @Param("example") ImgInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ImgInfo record, @Param("example") ImgInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ImgInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ImgInfo record);
}