package com.jinxin.manager.po;

import java.util.Date;

public class BbsMsg {
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column t_board_msg.id
	 *
	 * @mbg.generated
	 */
	private Integer id;

    /**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column t_board_msg.name
	 *
	 * @mbg.generated
	 */
	private String name;

	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column t_board_msg.email
	 *
	 * @mbg.generated
	 */
	private String email;

	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column t_board_msg.phone
	 *
	 * @mbg.generated
	 */
	private String phone;

	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column t_board_msg.message
	 *
	 * @mbg.generated
	 */
	private String message;

	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column t_board_msg.createtime
	 *
	 * @mbg.generated
	 */
	private Date createtime;

	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column t_board_msg.updatetime
	 *
	 * @mbg.generated
	 */
	private Date updatetime;

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column t_board_msg.id
	 *
	 * @return the value of t_board_msg.id
	 *
	 * @mbg.generated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column t_board_msg.id
	 *
	 * @param id the value for t_board_msg.id
	 *
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column t_board_msg.name
	 *
	 * @return the value of t_board_msg.name
	 *
	 * @mbg.generated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column t_board_msg.name
	 *
	 * @param name the value for t_board_msg.name
	 *
	 * @mbg.generated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column t_board_msg.email
	 *
	 * @return the value of t_board_msg.email
	 *
	 * @mbg.generated
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column t_board_msg.email
	 *
	 * @param email the value for t_board_msg.email
	 *
	 * @mbg.generated
	 */
	public void setEmail(String email) {
		this.email = email == null ? null : email.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column t_board_msg.phone
	 *
	 * @return the value of t_board_msg.phone
	 *
	 * @mbg.generated
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column t_board_msg.phone
	 *
	 * @param phone the value for t_board_msg.phone
	 *
	 * @mbg.generated
	 */
	public void setPhone(String phone) {
		this.phone = phone == null ? null : phone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column t_board_msg.message
	 *
	 * @return the value of t_board_msg.message
	 *
	 * @mbg.generated
	 */
	public String getMessage() {
		return message;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column t_board_msg.message
	 *
	 * @param message the value for t_board_msg.message
	 *
	 * @mbg.generated
	 */
	public void setMessage(String message) {
		this.message = message == null ? null : message.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column t_board_msg.createtime
	 *
	 * @return the value of t_board_msg.createtime
	 *
	 * @mbg.generated
	 */
	public Date getCreatetime() {
		return createtime;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column t_board_msg.createtime
	 *
	 * @param createtime the value for t_board_msg.createtime
	 *
	 * @mbg.generated
	 */
	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column t_board_msg.updatetime
	 *
	 * @return the value of t_board_msg.updatetime
	 *
	 * @mbg.generated
	 */
	public Date getUpdatetime() {
		return updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column t_board_msg.updatetime
	 *
	 * @param updatetime the value for t_board_msg.updatetime
	 *
	 * @mbg.generated
	 */
	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}
}