package com.jinxin.manager.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class BlogArticleExample {
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database table t_my_blog
	 *
	 * @mbg.generated
	 */
	protected String orderByClause;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database table t_my_blog
	 *
	 * @mbg.generated
	 */
	protected boolean distinct;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database table t_my_blog
	 *
	 * @mbg.generated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table t_my_blog
	 *
	 * @mbg.generated
	 */
	public BlogArticleExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table t_my_blog
	 *
	 * @mbg.generated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table t_my_blog
	 *
	 * @mbg.generated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table t_my_blog
	 *
	 * @mbg.generated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table t_my_blog
	 *
	 * @mbg.generated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table t_my_blog
	 *
	 * @mbg.generated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table t_my_blog
	 *
	 * @mbg.generated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table t_my_blog
	 *
	 * @mbg.generated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table t_my_blog
	 *
	 * @mbg.generated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table t_my_blog
	 *
	 * @mbg.generated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table t_my_blog
	 *
	 * @mbg.generated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator.
	 * This class corresponds to the database table t_my_blog
	 *
	 * @mbg.generated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andTitleIsNull() {
			addCriterion("title is null");
			return (Criteria) this;
		}

		public Criteria andTitleIsNotNull() {
			addCriterion("title is not null");
			return (Criteria) this;
		}

		public Criteria andTitleEqualTo(String value) {
			addCriterion("title =", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotEqualTo(String value) {
			addCriterion("title <>", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleGreaterThan(String value) {
			addCriterion("title >", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleGreaterThanOrEqualTo(String value) {
			addCriterion("title >=", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLessThan(String value) {
			addCriterion("title <", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLessThanOrEqualTo(String value) {
			addCriterion("title <=", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLike(String value) {
			addCriterion("title like", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotLike(String value) {
			addCriterion("title not like", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleIn(List<String> values) {
			addCriterion("title in", values, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotIn(List<String> values) {
			addCriterion("title not in", values, "title");
			return (Criteria) this;
		}

		public Criteria andTitleBetween(String value1, String value2) {
			addCriterion("title between", value1, value2, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotBetween(String value1, String value2) {
			addCriterion("title not between", value1, value2, "title");
			return (Criteria) this;
		}

		public Criteria andSummaryIsNull() {
			addCriterion("summary is null");
			return (Criteria) this;
		}

		public Criteria andSummaryIsNotNull() {
			addCriterion("summary is not null");
			return (Criteria) this;
		}

		public Criteria andSummaryEqualTo(String value) {
			addCriterion("summary =", value, "summary");
			return (Criteria) this;
		}

		public Criteria andSummaryNotEqualTo(String value) {
			addCriterion("summary <>", value, "summary");
			return (Criteria) this;
		}

		public Criteria andSummaryGreaterThan(String value) {
			addCriterion("summary >", value, "summary");
			return (Criteria) this;
		}

		public Criteria andSummaryGreaterThanOrEqualTo(String value) {
			addCriterion("summary >=", value, "summary");
			return (Criteria) this;
		}

		public Criteria andSummaryLessThan(String value) {
			addCriterion("summary <", value, "summary");
			return (Criteria) this;
		}

		public Criteria andSummaryLessThanOrEqualTo(String value) {
			addCriterion("summary <=", value, "summary");
			return (Criteria) this;
		}

		public Criteria andSummaryLike(String value) {
			addCriterion("summary like", value, "summary");
			return (Criteria) this;
		}

		public Criteria andSummaryNotLike(String value) {
			addCriterion("summary not like", value, "summary");
			return (Criteria) this;
		}

		public Criteria andSummaryIn(List<String> values) {
			addCriterion("summary in", values, "summary");
			return (Criteria) this;
		}

		public Criteria andSummaryNotIn(List<String> values) {
			addCriterion("summary not in", values, "summary");
			return (Criteria) this;
		}

		public Criteria andSummaryBetween(String value1, String value2) {
			addCriterion("summary between", value1, value2, "summary");
			return (Criteria) this;
		}

		public Criteria andSummaryNotBetween(String value1, String value2) {
			addCriterion("summary not between", value1, value2, "summary");
			return (Criteria) this;
		}

		public Criteria andArticleTypeIsNull() {
			addCriterion("articletype is null");
			return (Criteria) this;
		}

		public Criteria andArticleTypeIsNotNull() {
			addCriterion("articletype is not null");
			return (Criteria) this;
		}

		public Criteria andArticleTypeEqualTo(Integer value) {
			addCriterion("articletype =", value, "articleType");
			return (Criteria) this;
		}

		public Criteria andArticleTypeNotEqualTo(Integer value) {
			addCriterion("articletype <>", value, "articleType");
			return (Criteria) this;
		}

		public Criteria andArticleTypeGreaterThan(Integer value) {
			addCriterion("articletype >", value, "articleType");
			return (Criteria) this;
		}

		public Criteria andArticleTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("articletype >=", value, "articleType");
			return (Criteria) this;
		}

		public Criteria andArticleTypeLessThan(Integer value) {
			addCriterion("articletype <", value, "articleType");
			return (Criteria) this;
		}

		public Criteria andArticleTypeLessThanOrEqualTo(Integer value) {
			addCriterion("articletype <=", value, "articleType");
			return (Criteria) this;
		}

		public Criteria andArticleTypeIn(List<Integer> values) {
			addCriterion("articletype in", values, "articleType");
			return (Criteria) this;
		}

		public Criteria andArticleTypeNotIn(List<Integer> values) {
			addCriterion("articletype not in", values, "articleType");
			return (Criteria) this;
		}

		public Criteria andArticleTypeBetween(Integer value1, Integer value2) {
			addCriterion("articletype between", value1, value2, "articleType");
			return (Criteria) this;
		}

		public Criteria andArticleTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("articletype not between", value1, value2, "articleType");
			return (Criteria) this;
		}

		public Criteria andArticleIsNull() {
			addCriterion("article is null");
			return (Criteria) this;
		}

		public Criteria andArticleIsNotNull() {
			addCriterion("article is not null");
			return (Criteria) this;
		}

		public Criteria andArticleEqualTo(String value) {
			addCriterion("article =", value, "article");
			return (Criteria) this;
		}

		public Criteria andArticleNotEqualTo(String value) {
			addCriterion("article <>", value, "article");
			return (Criteria) this;
		}

		public Criteria andArticleGreaterThan(String value) {
			addCriterion("article >", value, "article");
			return (Criteria) this;
		}

		public Criteria andArticleGreaterThanOrEqualTo(String value) {
			addCriterion("article >=", value, "article");
			return (Criteria) this;
		}

		public Criteria andArticleLessThan(String value) {
			addCriterion("article <", value, "article");
			return (Criteria) this;
		}

		public Criteria andArticleLessThanOrEqualTo(String value) {
			addCriterion("article <=", value, "article");
			return (Criteria) this;
		}

		public Criteria andArticleLike(String value) {
			addCriterion("article like", value, "article");
			return (Criteria) this;
		}

		public Criteria andArticleNotLike(String value) {
			addCriterion("article not like", value, "article");
			return (Criteria) this;
		}

		public Criteria andArticleIn(List<String> values) {
			addCriterion("article in", values, "article");
			return (Criteria) this;
		}

		public Criteria andArticleNotIn(List<String> values) {
			addCriterion("article not in", values, "article");
			return (Criteria) this;
		}

		public Criteria andArticleBetween(String value1, String value2) {
			addCriterion("article between", value1, value2, "article");
			return (Criteria) this;
		}

		public Criteria andArticleNotBetween(String value1, String value2) {
			addCriterion("article not between", value1, value2, "article");
			return (Criteria) this;
		}

		public Criteria andSupportIsNull() {
			addCriterion("is_support is null");
			return (Criteria) this;
		}

		public Criteria andSupportIsNotNull() {
			addCriterion("is_support is not null");
			return (Criteria) this;
		}

		public Criteria andSupportEqualTo(Integer value) {
			addCriterion("is_support =", value, "support");
			return (Criteria) this;
		}

		public Criteria andSupportNotEqualTo(Integer value) {
			addCriterion("is_support <>", value, "support");
			return (Criteria) this;
		}

		public Criteria andSupportGreaterThan(Integer value) {
			addCriterion("is_support >", value, "support");
			return (Criteria) this;
		}

		public Criteria andSupportGreaterThanOrEqualTo(Integer value) {
			addCriterion("is_support >=", value, "support");
			return (Criteria) this;
		}

		public Criteria andSupportLessThan(Integer value) {
			addCriterion("is_support <", value, "support");
			return (Criteria) this;
		}

		public Criteria andSupportLessThanOrEqualTo(Integer value) {
			addCriterion("is_support <=", value, "support");
			return (Criteria) this;
		}

		public Criteria andSupportIn(List<Integer> values) {
			addCriterion("is_support in", values, "support");
			return (Criteria) this;
		}

		public Criteria andSupportNotIn(List<Integer> values) {
			addCriterion("is_support not in", values, "support");
			return (Criteria) this;
		}

		public Criteria andSupportBetween(Integer value1, Integer value2) {
			addCriterion("is_support between", value1, value2, "support");
			return (Criteria) this;
		}

		public Criteria andSupportNotBetween(Integer value1, Integer value2) {
			addCriterion("is_support not between", value1, value2, "support");
			return (Criteria) this;
		}

		public Criteria andSecretIsNull() {
			addCriterion("is_secret is null");
			return (Criteria) this;
		}

		public Criteria andSecretIsNotNull() {
			addCriterion("is_secret is not null");
			return (Criteria) this;
		}

		public Criteria andSecretEqualTo(Integer value) {
			addCriterion("is_secret =", value, "secret");
			return (Criteria) this;
		}

		public Criteria andSecretNotEqualTo(Integer value) {
			addCriterion("is_secret <>", value, "secret");
			return (Criteria) this;
		}

		public Criteria andSecretGreaterThan(Integer value) {
			addCriterion("is_secret >", value, "secret");
			return (Criteria) this;
		}

		public Criteria andSecretGreaterThanOrEqualTo(Integer value) {
			addCriterion("is_secret >=", value, "secret");
			return (Criteria) this;
		}

		public Criteria andSecretLessThan(Integer value) {
			addCriterion("is_secret <", value, "secret");
			return (Criteria) this;
		}

		public Criteria andSecretLessThanOrEqualTo(Integer value) {
			addCriterion("is_secret <=", value, "secret");
			return (Criteria) this;
		}

		public Criteria andSecretIn(List<Integer> values) {
			addCriterion("is_secret in", values, "secret");
			return (Criteria) this;
		}

		public Criteria andSecretNotIn(List<Integer> values) {
			addCriterion("is_secret not in", values, "secret");
			return (Criteria) this;
		}

		public Criteria andSecretBetween(Integer value1, Integer value2) {
			addCriterion("is_secret between", value1, value2, "secret");
			return (Criteria) this;
		}

		public Criteria andSecretNotBetween(Integer value1, Integer value2) {
			addCriterion("is_secret not between", value1, value2, "secret");
			return (Criteria) this;
		}

		public Criteria andCreattimeIsNull() {
			addCriterion("creattime is null");
			return (Criteria) this;
		}

		public Criteria andCreattimeIsNotNull() {
			addCriterion("creattime is not null");
			return (Criteria) this;
		}

		public Criteria andCreattimeEqualTo(Date value) {
			addCriterion("creattime =", value, "creattime");
			return (Criteria) this;
		}

		public Criteria andCreattimeNotEqualTo(Date value) {
			addCriterion("creattime <>", value, "creattime");
			return (Criteria) this;
		}

		public Criteria andCreattimeGreaterThan(Date value) {
			addCriterion("creattime >", value, "creattime");
			return (Criteria) this;
		}

		public Criteria andCreattimeGreaterThanOrEqualTo(Date value) {
			addCriterion("creattime >=", value, "creattime");
			return (Criteria) this;
		}

		public Criteria andCreattimeLessThan(Date value) {
			addCriterion("creattime <", value, "creattime");
			return (Criteria) this;
		}

		public Criteria andCreattimeLessThanOrEqualTo(Date value) {
			addCriterion("creattime <=", value, "creattime");
			return (Criteria) this;
		}

		public Criteria andCreattimeIn(List<Date> values) {
			addCriterion("creattime in", values, "creattime");
			return (Criteria) this;
		}

		public Criteria andCreattimeNotIn(List<Date> values) {
			addCriterion("creattime not in", values, "creattime");
			return (Criteria) this;
		}

		public Criteria andCreattimeBetween(Date value1, Date value2) {
			addCriterion("creattime between", value1, value2, "creattime");
			return (Criteria) this;
		}

		public Criteria andCreattimeNotBetween(Date value1, Date value2) {
			addCriterion("creattime not between", value1, value2, "creattime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeIsNull() {
			addCriterion("updatetime is null");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeIsNotNull() {
			addCriterion("updatetime is not null");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeEqualTo(Date value) {
			addCriterion("updatetime =", value, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeNotEqualTo(Date value) {
			addCriterion("updatetime <>", value, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeGreaterThan(Date value) {
			addCriterion("updatetime >", value, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeGreaterThanOrEqualTo(Date value) {
			addCriterion("updatetime >=", value, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeLessThan(Date value) {
			addCriterion("updatetime <", value, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeLessThanOrEqualTo(Date value) {
			addCriterion("updatetime <=", value, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeIn(List<Date> values) {
			addCriterion("updatetime in", values, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeNotIn(List<Date> values) {
			addCriterion("updatetime not in", values, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeBetween(Date value1, Date value2) {
			addCriterion("updatetime between", value1, value2, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeNotBetween(Date value1, Date value2) {
			addCriterion("updatetime not between", value1, value2, "updatetime");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator.
	 * This class corresponds to the database table t_my_blog
	 *
	 * @mbg.generated do_not_delete_during_merge
	 */
	public static class Criteria extends GeneratedCriteria {

		protected Criteria() {
			super();
		}
	}

	/**
	 * This class was generated by MyBatis Generator.
	 * This class corresponds to the database table t_my_blog
	 *
	 * @mbg.generated
	 */
	public static class Criterion {
		private String condition;

		private Object value;

		private Object secondValue;

		private boolean noValue;

		private boolean singleValue;

		private boolean betweenValue;

		private boolean listValue;

		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}
}